### PR TITLE
Hi, they are serving gomp2p:// urls again.

### PR DESCRIPTION
**Pull request by fj128**
... even for SQ. Strangely, the real url inside is not url-escaped, as it was with SQTest if I recall correctly, so here's a simple patch that works as of now.

### CODE REVIEW

**Comment by sjp** [comment]
Ah, so this is an issue only affecting users with premium tickets?

I've been having no trouble with SQTest, so I guess that's why I haven't noticed.

**Comment by fj128** [comment]
On Wed, May 18, 2011 at 5:30 PM, sjp
reply@reply.github.com
wrote:

> Ah, so this is an issue only affecting users with premium tickets?
> 
> I've been having no trouble with SQTest, so I guess that's why I haven't noticed.

W-well. I was kinda confused, sorry.

I did have a premium ticket for the previous season, and it worked
flawlessly. (Fun fact, it also worked for the first day of GSTL =) )

Then I switched from HQ to SQ instead of SQTest for some reason (and
by that I mean "by mistake"), and discovered that it works too, but I
have to do what I did. Which, as I see now, is pretty much the same
thing as you do for SQTest, except that here you search for 'http%3a'
before urlunquote, while up there I check if it uses gomp2p protocol
and then search for "LiveAddr=" _after_ urlunquote (which was the most
confusing part for me, as I totally missed the urlunquote earlier and
assumed that in the SQ case they pass unquoted url somehow).

Anyway. All that means that more than half of that code can be
eliminated -- we don't have to check the quality at all, we can simply
try to delete the first part of the string if it matches
'^gomp2p.*LiveAddr=' and be done with it.

The only weird thing remaining is that "regexResult =
re.sub(r'&quot;', '', regexResult)" that you do in the SQTest case,
but not in the HQ case. It seems to be unnecessary now (SQTest works
with it commented out) -- did you need that because you used a
different regexp at some point before? If so, I'll clean all that up,
see if it works tomorrow and commit then!

**Comment by sjp** [comment]
I've tested your patches and I'm very happy with them :).

Will merge them shortly, thanks.

**Comment by fj128** [comment]
Thank you for your kind words!

By the way, I just noticed -- the way I do it now, there _is_ a stray
"&quot;" being left in the url =) But it's OK, as it gets interpreted
as a request parameter and ignored by their servers.

On Thu, May 19, 2011 at 2:31 PM, sjp
reply@reply.github.com
wrote:

**Comment by sjp** [comment]
Yeah, I'll leave it for now. I might get around to getting rid of the &quot; if another patch is required.

Seeing as it's purely cosmetic I don't think it's worth bothering with at the moment.

Thanks again for the patch!

**Pull request merged**
