### PR TITLE
Pssst! There's a typo in the alternate stream code!

### PR DESCRIPTION
**Pull request by fj128**
That is all.

### CODE REVIEW

**Comment by sjp** [comment]
Hah, I just noticed that this evening too and have fixed it locally, but that doesn't fix the problem for me.

Will incorporate this change as part of a fix for alternate streams.

Thanks anyway.

**Comment by willth** [comment]
Oh dang, just submitted a pull req for this. Beat me by 13 min!

**Comment by willth** [comment]
Btw dual streams on gomtv right now are working fine for me. (GSL S1 - Code A, Round1, Day1)

**Comment by sjp** [comment]
I think the issue I ran into was due to issues on GOMtv's end, which sent me on a wild goose chase.

I'll be pushing out a new release before the next airing of the GSL.

**Comment by sjp** [comment]
The fixes have been pushed out as of commit e3e205319d48d6a431183bcf2170cbb3897269c8.

Thanks for the heads up :).

**Pull request closed without merging**
